changesetBaseRefs:
  - latest
  - origin/latest
  - next
  - origin/next

packageExtensions:
  rollup-plugin-swc3@*:
    peerDependenciesMeta:
      rollup:
        optional: true

yarnPath: .yarn/releases/yarn-3.6.4.cjs
