changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

packageExtensions:
  "@jest/core@*":
    peerDependencies:
      ts-node: "*"
  jest-cli@*:
    peerDependencies:
      ts-node: "*"
  jest@*:
    peerDependencies:
      ts-node: "*"
    peerDependenciesMeta:
      ts-node:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.5.1.cjs
