name: 'Build website'

on:
  pull_request:
    branches:
      - main

jobs:
  build-website:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 16
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - name: Build website
        working-directory: website
        run: yarn run build
